import React from "react";
import Head from "next/head";
import NavBar from "~/components/NavBar";

const Layout = ({ children }) => {
  return (
    <section className="min-h-screen bg-zinc-900 text-slate-200">
      <Head>
        <title>Campaign list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <main className="mx-auto container w-11/12">{children}</main>
    </section>
  );
};

export default Layout;
