import React from "react";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <div className="min-h-screen bg-zinc-900 text-slate-200">
      <Head>
        <title>Campaign list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav></nav>
      <main className="mx-auto w-11/12">{children}</main>
    </div>
  );
};

export default Layout;
